services:
    mongo:
        container_name: mongodb
        image: mongo:latest
        ports:
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: squire
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: squire
        volumes:
            - ./dev/db:/data/db
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro